/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/explore` | `/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/TabBarBackground`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}/explore` | `/app/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/components/HelloWave`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ParallaxScrollView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/TabBarBackground`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/app/explore${`?${string}` | `#${string}` | ''}` | `/app${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `/components/Collapsible${`?${string}` | `#${string}` | ''}` | `/components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/components/HapticTab${`?${string}` | `#${string}` | ''}` | `/components/HelloWave${`?${string}` | `#${string}` | ''}` | `/components/ParallaxScrollView${`?${string}` | `#${string}` | ''}` | `/components/ThemedText${`?${string}` | `#${string}` | ''}` | `/components/ThemedView${`?${string}` | `#${string}` | ''}` | `/components/ui/IconSymbol${`?${string}` | `#${string}` | ''}` | `/components/ui/TabBarBackground${`?${string}` | `#${string}` | ''}` | `/constants/Colors${`?${string}` | `#${string}` | ''}` | `/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}/explore` | `/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/app${'/(tabs)'}` | `/app`; params?: Router.UnknownInputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/TabBarBackground`; params?: Router.UnknownInputParams; } | { pathname: `/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | `/app/+not-found` | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
